services:
  web:
    build: .
    command: >
      sh -c "python src/manage.py migrate &&
             python src/manage.py ensure_superuser &&
             python src/manage.py runserver 0.0.0.0:8000"
    volumes:
      - unison:/data
    ports:
      - "${APP_BIND_PORT:-8234}:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - unison_net

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - unison_net

networks:
  unison_net:
    driver: bridge

volumes:
  postgres_data:
  unison:
